services:
  database-auth-dev:
    image: mysql:8.0.30-debian
    ports:
      - 3307:3306
    volumes:
      - auth-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-auth

  database-faculty-dev:
    image: mysql:8.0.30-debian
    ports:
      - 3308:3306
    volumes:
      - faculty-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-faculty

  database-subject-dev:
    image: mysql:8.0.30-debian
    ports:
      - 3309:3306
    volumes:
      - subject-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-subject

  database-exam-dev:
    image: mysql:8.0.30-debian
    ports:
      - 3310:3306
    volumes:
      - exam-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-exam

  database-crm-dev:
    image: mysql:8.0.30-debian
    ports:
      - 3311:3306
    volumes:
      - crm-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-crm

  database-notify-dev:
    image: mysql:8.0.30-debian
    ports:
      - 3312:3306
    volumes:
      - notify-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-notify

  database-audit-dev:
    image: mysql:8.0.30-debian
    ports:
      - 3313:3306
    volumes:
      - audit-data-dev:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms-audit

  redis-dev:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data-dev:/data

volumes:
  auth-data-dev:
  faculty-data-dev:
  subject-data-dev:
  exam-data-dev:
  crm-data-dev:
  notify-data-dev:
  audit-data-dev:
  redis-data-dev:
