server:
  port: 8086

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3312/lms-notify?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_empty

springdoc:
  api-docs:
    path: /docs

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  secret: ${JWT_SECRET:GieJX^>%Pd;Z]#&?kmZY4SRZNlWsjr%JJiH!q9KM~,Zd./[oh*=dus&p_M3Ab#B}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:}
    username: ${TELEGRAM_BOT_USERNAME:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
