spring:
  datasource:
    url: jdbc:mysql://database-subject:3306/lms-subject?createDatabaseIfNotExist=true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://backend-discovery-server:8761/eureka
